In [3]:
import pandas as pd
from sqlalchemy import create_engine, text

In [4]:
USERNAME = 'postgres'
PASSWORD = '180404'
HOST = 'localhost'
PORT = '5433'
DB_NAME = 'store_performance_db'

engine = create_engine(f'postgresql+psycopg2://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DB_NAME}')

In [5]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';"))
    print(result.fetchall())

[('regions',), ('store',), ('store_performance',), ('store_products',), ('customer',)]

## transactions import

In [6]:
transactions = pd.read_csv('FoodMart-Transactions-1997.csv')
transactions.head()

  transaction_date  stock_date  product_id  customer_id  store_id  quantity
0         1/1/1997  12/31/1996         869         3449         6         5
1         1/1/1997  12/31/1996        1472         3449         6         3
2         1/1/1997  12/28/1996          76         3449         6         4
3         1/1/1997  12/26/1996         320         3449         6         3
4         1/1/1997  12/25/1996           4         3449         6         4

In [7]:
#transactions.to_sql('store_performance', con=engine, if_exists='replace', index=False)

In [8]:
with engine.connect() as conn:
    count = conn.execute(text("SELECT COUNT(*) FROM store_performance;")).scalar()
    print('Rows now in PostgreSQL:', count)

    sample = conn.execute(text("SELECT * FROM store_performance LIMIT 5;")).fetchall()
    print('Sample data:', sample)

Rows now in PostgreSQL: 86837
Sample data: [('1/1/1997', '12/31/1996', 869, 3449, 6, 5), ('1/1/1997', '12/31/1996', 1472, 3449, 6, 3), ('1/1/1997', '12/28/1996', 76, 3449, 6, 4), ('1/1/1997', '12/26/1996', 320, 3449, 6, 3), ('1/1/1997', '12/25/1996', 4, 3449, 6, 4)]

## product import

In [9]:
product = pd.read_csv('Product-Lookup.csv')
product.head()

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
0,1,Washington,Washington Berry Juice,90748583674,2.85,0.94,8.39,NaN,NaN
1,2,Washington,Washington Mango Drink,96516502499,0.74,0.26,7.42,NaN,1.0
2,3,Washington,Washington Strawberry Drink,58427771925,0.83,0.40,13.10,1.0,1.0
3,4,Washington,Washington Cream Soda,64412155747,3.64,1.64,10.60,1.0,NaN
4,5,Washington,Washington Diet Soda,85561191439,2.19,0.77,6.66,1.0,NaN

In [10]:
#product.to_sql('store_products', con=engine, if_exists='replace', index=False)

In [11]:
with engine.connect() as conn:
    count = conn.execute(text("SELECT COUNT(*) FROM store_products;")).scalar()
    print('Rows now in PostgreSQL:', count)

    sample = conn.execute(text("SELECT * FROM store_products LIMIT 5;")).fetchall()
    print('Sample data:', sample)

Rows now in PostgreSQL: 1560
Sample data: [(1, 'Washington', 'Washington Berry Juice', 90748583674, 2.85, 0.94, 8.39, None, None), (2, 'Washington', 'Washington Mango Drink', 96516502499, 0.74, 0.26, 7.42, None, 1.0), (3, 'Washington', 'Washington Strawberry Drink', 58427771925, 0.83, 0.4, 13.1, 1.0, 1.0), (4, 'Washington', 'Washington Cream Soda', 64412155747, 3.64, 1.64, 10.6, 1.0, None), (5, 'Washington', 'Washington Diet Soda', 85561191439, 2.19, 0.77, 6.66, 1.0, None)]

## import customer

In [12]:
customer = pd.read_csv('Customer-Lookup.csv')
customer.head()

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,marital_status,yearly_income,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner
0,1,87462024688,Sheri,Nowmer,2433 Bailey Road,Tlaxiaco,Oaxaca,15057,Mexico,8/26/1961,M,$30K - $50K,F,4,2,Partial High School,9/10/1991,Bronze,Skilled Manual,Y
1,2,87470586299,Derrick,Whelply,2219 Dewing Avenue,Sooke,BC,17172,Canada,7/3/1915,S,$70K - $90K,M,1,0,Partial High School,3/11/1993,Bronze,Professional,N
2,3,87475757600,Jeanne,Derry,7640 First Ave.,Issaquah,WA,73980,USA,6/21/1910,M,$50K - $70K,F,1,1,Bachelors Degree,6/11/1991,Bronze,Professional,Y
3,4,87500482201,Michael,Spence,337 Tosca Way,Burnaby,BC,74674,Canada,6/20/1969,M,$10K - $30K,M,4,4,Partial High School,5/21/1994,Normal,Skilled Manual,N
4,5,87514054179,Maya,Gutierrez,8668 Via Neruda,Novato,CA,57355,USA,5/10/1951,S,$30K - $50K,F,3,0,Partial College,8/21/1992,Silver,Manual,N

In [13]:
#customer.to_sql('customer', con=engine, if_exists='replace', index=False)

In [14]:
with engine.connect() as conn:
    count = conn.execute(text("SELECT COUNT(*) FROM customer;")).scalar()
    print('Rows now in PostgreSQL:', count)

    sample = conn.execute(text("SELECT * FROM customer LIMIT 5;")).fetchall()
    print('Sample data:', sample)

Rows now in PostgreSQL: 10281
Sample data: [(1, 87462024688, 'Sheri', 'Nowmer', '2433 Bailey Road', 'Tlaxiaco', 'Oaxaca', 15057, 'Mexico', '8/26/1961', 'M', '$30K - $50K', 'F', 4, 2, 'Partial High School', '9/10/1991', 'Bronze', 'Skilled Manual', 'Y'), (2, 87470586299, 'Derrick', 'Whelply', '2219 Dewing Avenue', 'Sooke', 'BC', 17172, 'Canada', '7/3/1915', 'S', '$70K - $90K', 'M', 1, 0, 'Partial High School', '3/11/1993', 'Bronze', 'Professional', 'N'), (3, 87475757600, 'Jeanne', 'Derry', '7640 First Ave.', 'Issaquah', 'WA', 73980, 'USA', '6/21/1910', 'M', '$50K - $70K', 'F', 1, 1, 'Bachelors Degree', '6/11/1991', 'Bronze', 'Professional', 'Y'), (4, 87500482201, 'Michael', 'Spence', '337 Tosca Way', 'Burnaby', 'BC', 74674, 'Canada', '6/20/1969', 'M', '$10K - $30K', 'M', 4, 4, 'Partial High School', '5/21/1994', 'Normal', 'Skilled Manual', 'N'), (5, 87514054179, 'Maya', 'Gutierrez', '8668 Via Neruda', 'Novato', 'CA', 57355, 'USA', '5/10/1951', 'S', '$30K - $50K', 'F', 3, 0, 'Partial College', '8/21/1992', 'Silver', 'Manual', 'N')]

## import region

In [15]:
region = pd.read_csv('Region-Lookup.csv')
region.head()

   region_id sales_district    sales_region
0          1  San Francisco    Central West
1          2    Mexico City  Mexico Central
2          3    Los Angeles      South West
3          4    Guadalajara     Mexico West
4          5      Vancouver     Canada West

In [16]:
#region.to_sql('regions', con=engine, if_exists='replace', index=False)

In [17]:
with engine.connect() as conn:
    count = conn.execute(text("SELECT COUNT(*) FROM regions;")).scalar()
    print('Rows now in PostgreSQL:', count)

    sample = conn.execute(text("SELECT * FROM regions LIMIT 5;")).fetchall()
    print('Sample data:', sample)

Rows now in PostgreSQL: 109
Sample data: [(1, 'San Francisco', 'Central West'), (2, 'Mexico City', 'Mexico Central'), (3, 'Los Angeles', 'South West'), (4, 'Guadalajara', 'Mexico West'), (5, 'Vancouver', 'Canada West')]

## import store

In [18]:
store = pd.read_csv('Store-Lookup.csv')
store.head()

,store_id,region_id,store_type,store_name,store_street_address,store_city,store_state,store_country,store_phone,first_opened_date,last_remodel_date,total_sqft,grocery_sqft
0,1,28,Supermarket,Store 1,2853 Bailey Rd,Acapulco,Guerrero,Mexico,262-555-5124,1/9/1982,12/5/1990,23593,17475
1,2,78,Small Grocery,Store 2,5203 Catanzaro Way,Bellingham,WA,USA,605-555-8203,4/2/1970,6/4/1973,28206,22271
2,3,76,Supermarket,Store 3,1501 Ramsey Circle,Bremerton,WA,USA,509-555-1596,6/14/1959,11/19/1967,39696,24390
3,4,27,Gourmet Supermarket,Store 4,433 St George Dr,Camacho,Zacatecas,Mexico,304-555-1474,9/27/1994,12/1/1995,23759,16844
4,5,4,Small Grocery,Store 5,1250 Coggins Drive,Guadalajara,Jalisco,Mexico,801-555-4324,9/18/1978,6/29/1991,24597,15012

In [19]:
#store.to_sql('store', con=engine, if_exists='replace', index=False)

In [20]:
with engine.connect() as conn:
    count = conn.execute(text("SELECT COUNT(*) FROM store;")).scalar()
    print('Rows now in PostgreSQL:', count)

    sample = conn.execute(text("SELECT * FROM store LIMIT 5;")).fetchall()
    print('Sample data:', sample)

Rows now in PostgreSQL: 24
Sample data: [(1, 28, 'Supermarket', 'Store 1', '2853 Bailey Rd', 'Acapulco', 'Guerrero', 'Mexico', '262-555-5124', '1/9/1982', '12/5/1990', 23593, 17475), (2, 78, 'Small Grocery', 'Store 2', '5203 Catanzaro Way', 'Bellingham', 'WA', 'USA', '605-555-8203', '4/2/1970', '6/4/1973', 28206, 22271), (3, 76, 'Supermarket', 'Store 3', '1501 Ramsey Circle', 'Bremerton', 'WA', 'USA', '509-555-1596', '6/14/1959', '11/19/1967', 39696, 24390), (4, 27, 'Gourmet Supermarket', 'Store 4', '433 St George Dr', 'Camacho', 'Zacatecas', 'Mexico', '304-555-1474', '9/27/1994', '12/1/1995', 23759, 16844), (5, 4, 'Small Grocery', 'Store 5', '1250 Coggins Drive', 'Guadalajara', 'Jalisco', 'Mexico', '801-555-4324', '9/18/1978', '6/29/1991', 24597, 15012)]

In [23]:
customer.dtypes

customer_id                 int64
customer_acct_num           int64
first_name                 object
last_name                  object
customer_address           object
customer_city              object
customer_state_province    object
customer_postal_code        int64
customer_country           object
birthdate                  object
marital_status             object
yearly_income              object
gender                     object
total_children              int64
num_children_at_home        int64
education                  object
acct_open_date             object
member_card                object
occupation                 object
homeowner                  object
dtype: object

In [36]:

customer['birthdate'] = pd.to_datetime(customer['birthdate'])
customer['customer_acct_num'] = customer['customer_acct_num'].astype(str)
customer['customer_postal_code'] = customer['customer_postal_code'].astype(str)
customer['acct_open_date'] = pd.to_datetime(customer['acct_open_date'])
customer['homeowner'] = customer['homeowner'].map({'Y': True, 'N': False}).astype('boolean')

customer.dtypes

customer_id                         int64
customer_acct_num                  object
first_name                         object
last_name                          object
customer_address                   object
customer_city                      object
customer_state_province            object
customer_postal_code               object
customer_country                   object
birthdate                  datetime64[ns]
marital_status                     object
yearly_income                      object
gender                             object
total_children                      int64
num_children_at_home                int64
education                          object
acct_open_date             datetime64[ns]
member_card                        object
occupation                         object
homeowner                         boolean
dtype: object

In [25]:
store['first_opened_date'] = pd.to_datetime(store['first_opened_date'])
store['last_remodel_date'] = pd.to_datetime(store['last_remodel_date'])

store.dtypes

store_id                         int64
region_id                        int64
store_type                      object
store_name                      object
store_street_address            object
store_city                      object
store_state                     object
store_country                   object
store_phone                     object
first_opened_date       datetime64[ns]
last_remodel_date       datetime64[ns]
total_sqft                       int64
grocery_sqft                     int64
dtype: object

In [40]:
transactions['transaction_date'] = pd.to_datetime(transactions['transaction_date'])
transactions['transaction_id'] = (transactions.index+1).astype(int)
transactions['stock_date'] = pd.to_datetime(transactions['stock_date'])

transactions.dtypes

transaction_date    datetime64[ns]
stock_date          datetime64[ns]
product_id                   int64
customer_id                  int64
store_id                     int64
quantity                     int64
transaction_id               int64
dtype: object

In [41]:
transactions

,transaction_date,stock_date,product_id,customer_id,store_id,quantity,transaction_id
0,1997-01-01,1996-12-31,869,3449,6,5,1
1,1997-01-01,1996-12-31,1472,3449,6,3,2
2,1997-01-01,1996-12-28,76,3449,6,4,3
3,1997-01-01,1996-12-26,320,3449,6,3,4
4,1997-01-01,1996-12-25,4,3449,6,4,5
...,...,...,...,...,...,...,...
86832,1997-12-30,1997-12-29,1376,7043,14,2,86833
86833,1997-12-30,1997-12-26,1380,7043,14,1,86834
86834,1997-12-30,1997-12-23,637,7043,14,2,86835
86835,1997-12-30,1997-12-29,930,2145,14,1,86836
86836,1997-12-30,1997-12-28,427,2145,14,2,86837

In [33]:
product['product_sku'] = product['product_sku'].astype(str)
product['recyclable'] = product['recyclable'].astype('boolean')
product['low_fat'] = product['low_fat'].astype('boolean')

In [37]:
product

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
0,1,Washington,Washington Berry Juice,90748583674,2.85,0.94,8.39,<NA>,<NA>
1,2,Washington,Washington Mango Drink,96516502499,0.74,0.26,7.42,<NA>,True
2,3,Washington,Washington Strawberry Drink,58427771925,0.83,0.40,13.10,True,True
3,4,Washington,Washington Cream Soda,64412155747,3.64,1.64,10.60,True,<NA>
4,5,Washington,Washington Diet Soda,85561191439,2.19,0.77,6.66,True,<NA>
...,...,...,...,...,...,...,...,...,...
1555,1556,CDR,CDR Creamy Peanut Butter,29538288712,2.65,1.14,6.94,True,True
1556,1557,CDR,CDR Strawberry Preserves,50687324404,1.20,0.48,15.40,True,<NA>
1557,1558,CDR,CDR Extra Chunky Peanut Butter,84930775761,2.16,0.82,11.50,<NA>,True
1558,1559,CDR,CDR Apple Preserves,75317577719,1.62,0.62,21.00,<NA>,<NA>
1559,1560,CDR,CDR Grape Jelly,54896665215,1.60,0.74,12.50,<NA>,True

## duplicate values

#### full row duplicates

In [146]:
# 1. transactions
print(f"Transactions - duplicates: {transactions.drop(columns=['transaction_id']).duplicated().sum()}")

# 2. customer
print(f"Customer - duplicates: {customer.drop(columns=['customer_id']).duplicated().sum()}")

# 3. product
print(f"Product - duplicates: {product.drop(columns=['product_id']).duplicated().sum()}")

# 4. store
print(f"Store - duplicates: {store.drop(columns=['store_id']).duplicated().sum()}")

# 5. region
print(f"Region - duplicates: {region.drop(columns=['region_id']).duplicated().sum()}")

Transactions - duplicates: 1
Customer - duplicates: 0
Product - duplicates: 0
Store - duplicates: 0
Region - duplicates: 87

In [160]:
mask = transactions.drop(columns=['transaction_id']).duplicated(keep='first')
transactions = transactions[~mask].reset_index(drop=True)

In [161]:
mask = transactions.drop(columns=['transaction_id']).duplicated(keep=False)
print(transactions[mask])

Empty DataFrame
Columns: [transaction_date, stock_date, product_id, customer_id, store_id, quantity, transaction_id]
Index: []

In [ ]:
# recreate transaction_id to account for the dropped duplicates 
transactions['transaction_id'] = transactions.index + 1

#### primary key duplicates

In [67]:
# 1. transactions_id duplicates
print(f"Duplicate transaction_id: {transactions.duplicated(subset=['transaction_id']).sum()}")

# 2. customer_id duplicates
print(f"Duplicate customer_id: {customer.duplicated(subset=['customer_id']).sum()}")   

# 3. product_id duplicates
print(f"Duplicate product_id: {product.duplicated(subset=['product_id']).sum()}")

# 4. store_id duplicates
print(f"Duplicate store_id: {store.duplicated(subset=['store_id']).sum()}")

# 5. region_id duplicates
print(f"Duplicate region_id: {region.duplicated(subset=['region_id']).sum()}")

Duplicate transaction_id: 0
Duplicate customer_id: 0
Duplicate product_id: 0
Duplicate store_id: 0
Duplicate region_id: 0

#### region duplicates

In [170]:
#returns only the unique values
print(region[['sales_district', 'sales_region']].drop_duplicates())
unique_rows = region[['sales_district', 'sales_region']].drop_duplicates()
print(f'The unique rows amount to {len(unique_rows)}')
print(f'The actual rows amount to {len(region)}')

   sales_district    sales_region
0   San Francisco    Central West
1     Mexico City  Mexico Central
2     Los Angeles      South West
3     Guadalajara     Mexico West
4       Vancouver     Canada West
5        Victoria     Canada West
6       San Diego      South West
17        Seattle      North West
21       Portland      North West
22          Salem      North West
23        Orizaba  Mexico Central
24        Hidalgo  Mexico Central
25         Marida    Mexico South
26        Camacho  Mexico Central
27       Acapulco     Mexico West
29       Tlaxiaco    Mexico South
75      Bremerton      North West
77     Bellingham      North West
83         Tacoma      North West
86        Spokane      North West
87    Walla Walla      North West
88         Yakima      North West
The unique rows amount to 22
The actual rows amount to 109

In [173]:
mask_2 = region.drop(columns=['region_id']).duplicated(keep='first')
region = region[~mask_2].reset_index(drop=True)

region

    region_id sales_district    sales_region
0           1  San Francisco    Central West
1           2    Mexico City  Mexico Central
2           3    Los Angeles      South West
3           4    Guadalajara     Mexico West
4           5      Vancouver     Canada West
5           6       Victoria     Canada West
6           7      San Diego      South West
7          18        Seattle      North West
8          22       Portland      North West
9          23          Salem      North West
10         24        Orizaba  Mexico Central
11         25        Hidalgo  Mexico Central
12         26         Marida    Mexico South
13         27        Camacho  Mexico Central
14         28       Acapulco     Mexico West
15         30       Tlaxiaco    Mexico South
16         76      Bremerton      North West
17         78     Bellingham      North West
18         84         Tacoma      North West
19         87        Spokane      North West
20         88    Walla Walla      North West
21         89         Yakima      North West

In [175]:
# rest the region_id to match the new row order after dropping duplicates
region['region_id'] = region.index + 1

region

    region_id sales_district    sales_region
0           1  San Francisco    Central West
1           2    Mexico City  Mexico Central
2           3    Los Angeles      South West
3           4    Guadalajara     Mexico West
4           5      Vancouver     Canada West
5           6       Victoria     Canada West
6           7      San Diego      South West
7           8        Seattle      North West
8           9       Portland      North West
9          10          Salem      North West
10         11        Orizaba  Mexico Central
11         12        Hidalgo  Mexico Central
12         13         Marida    Mexico South
13         14        Camacho  Mexico Central
14         15       Acapulco     Mexico West
15         16       Tlaxiaco    Mexico South
16         17      Bremerton      North West
17         18     Bellingham      North West
18         19         Tacoma      North West
19         20        Spokane      North West
20         21    Walla Walla      North West
21         22         Yakima      North West

## NA Values

### checking for null values

In [77]:
tables = ['store_performance', 'store', 'customer', 'store_products', 'regions']

null_summary = []
for table in tables:
    df = pd.read_sql(f"SELECT * FROM {table}", engine)
    nulls = df.isnull().sum()
    nulls = nulls[nulls > 0]  # only show columns with nulls
    for col, count in nulls.items():
        null_summary.append({'table': table, 'column': col, 'null_count': count})

pd.DataFrame(null_summary).sort_values(['table', 'null_count'], ascending=[True, False])

            table      column  null_count
0        customer   last_name           1
2  store_products     low_fat        1008
1  store_products  recyclable         687

In [ ]:
#decided to let this NaN value be
pd.DataFrame(null_summary).sort_values(['table', 'null_count'], ascending=[True, False])
customer[customer['last_name'].isnull()]

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,marital_status,yearly_income,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner
5139,5140,40265998244,Robert,NaN,2874 Tice,Santa Fe,DF,55238,Mexico,1917-04-18,S,$70K - $90K,F,1,0,Graduate Degree,1991-02-10,Silver,Management,False

In [95]:
product

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
0,1,Washington,Washington Berry Juice,90748583674,2.85,0.94,8.39,False,False
1,2,Washington,Washington Mango Drink,96516502499,0.74,0.26,7.42,False,True
2,3,Washington,Washington Strawberry Drink,58427771925,0.83,0.40,13.10,True,True
3,4,Washington,Washington Cream Soda,64412155747,3.64,1.64,10.60,True,False
4,5,Washington,Washington Diet Soda,85561191439,2.19,0.77,6.66,True,False
...,...,...,...,...,...,...,...,...,...
1555,1556,CDR,CDR Creamy Peanut Butter,29538288712,2.65,1.14,6.94,True,True
1556,1557,CDR,CDR Strawberry Preserves,50687324404,1.20,0.48,15.40,True,False
1557,1558,CDR,CDR Extra Chunky Peanut Butter,84930775761,2.16,0.82,11.50,False,True
1558,1559,CDR,CDR Apple Preserves,75317577719,1.62,0.62,21.00,False,False
1559,1560,CDR,CDR Grape Jelly,54896665215,1.60,0.74,12.50,False,True

### export back to sql

In [81]:
product['recyclable'] = product['recyclable'].fillna(False)
product['low_fat']    = product['low_fat'].fillna(False)

In [91]:
transactions.dtypes

transaction_date    datetime64[ns]
stock_date          datetime64[ns]
product_id                   int64
customer_id                  int64
store_id                     int64
quantity                     int64
transaction_id               int64
dtype: object

In [93]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';"))
    print(result.fetchall())

[('regions',), ('store',), ('store_performance',), ('store_products',), ('customer',)]

In [94]:
transactions.to_sql('store_performance', con=engine, if_exists='replace', index=False)

837

In [98]:
product.dtypes

product_id                int64
product_brand            object
product_name             object
product_sku              object
product_retail_price    float64
product_cost            float64
product_weight          float64
recyclable              boolean
low_fat                 boolean
dtype: object

In [99]:
product.to_sql('store_products', con=engine, if_exists='replace', index=False)

560

In [118]:
customer['customer_state_province'].value_counts()

customer_state_province
CA           4222
WA           2086
BC           1717
OR           1051
DF            347
Zacatecas     191
Guerrero      106
Jalisco       104
Yucatan        99
Mexico         97
Veracruz       93
Oaxaca         90
Sinaloa        78
Name: count, dtype: int64

In [126]:
customer['customer_state_province'].replace('CA', 'California', inplace=True)

In [127]:
customer['customer_state_province'].replace('WA', 'Washington', inplace=True)

In [128]:
customer['customer_state_province'].replace('BC', 'British Columbia', inplace=True)

In [129]:
customer['customer_state_province'].replace('OR', 'Oregon', inplace=True)

In [130]:
customer['customer_state_province'].replace('DF', 'Distrito Federal', inplace=True)

In [131]:
customer['customer_state_province'].value_counts()

customer_state_province
California          4222
Washington          2086
British Columbia    1717
Oregon              1051
Distrito Federal     347
Zacatecas            191
Guerrero             106
Jalisco              104
Yucatan               99
Mexico                97
Veracruz              93
Oaxaca                90
Sinaloa               78
Name: count, dtype: int64

In [132]:
customer.to_sql('customer', con=engine, if_exists='replace', index=False)

281

In [176]:
region.to_sql('regions', con=engine, if_exists='replace', index=False)

22

In [182]:
store.replace({'store_state': {'CA': 'California', 'WA': 'Washington', 'BC': 'British Columbia', 'OR': 'Oregon', 'DF': 'Distrito Federal'}}, inplace=True)

In [184]:
store['store_state'].value_counts()

store_state
Washington          7
California          4
Zacatecas           3
British Columbia    2
Oregon              2
Distrito Federal    2
Guerrero            1
Jalisco             1
Yucatan             1
Veracruz            1
Name: count, dtype: int64

In [185]:
store.to_sql('store', con=engine, if_exists='replace', index=False)

24